### ISSUE TITLE
오픈 타이밍 통일하기?

### ISSUE THREAD

**Issue by riseshia** [weirdmeetup/advent-calendar#21]
## Now

- 각 타임존의 날짜가 바뀌는 시점에 공개되고 있음
- 타임존에 따라서 url이 공개되는 시점이 다름

## Candiate Solution

- +00으로 통일한다
- 주 사용자는 한국이므로 +09로 통일한다
- URL이 존재하는 경우 그냥 공개한다 (Ruby advent-calendar 스타일)
- 그대로 방치한다.

**Comment by riseshia** [comment]
@minieetea 3번, 4번을 밀어볼까 하는데 어떠세요? > <

**Comment by minieetea** [comment]
@riseshia 2번으로 해주면 안되나요 ㅋㅋ

**Comment by riseshia** [comment]
@minieetea 합시다<

**Comment by riseshia** [comment]
쿠도님 확인 받고 클로즈합니다 'ㅅ'/

**Comment by riseshia** [comment]
곰개발님의 컨펌 확인했으므로 닫습니다
